[server]
bind_addr = " " # IP PÃšBLICA
port = 4444 # MODIFICAR PUERTO
max_connections = 10
banner = true

[persistence]
enabled = true
method = "startup"  # registry, startup, scheduled, service